### ISSUE TITLE
Responsiveness in mobile devices

### ISSUE THREAD

**Issue by rashil2000** [rashil2000/d-syfer#5]
Media screen attributes not working on mobile devices, however they do work on desktops

**Comment by meganindya** [comment]
Can I address this issue?

**Comment by msatul1305** [comment]
i am interested.

**Comment by msatul1305** [comment]
Check #13

**Comment by msatul1305** [comment]
should we add bootstrap also?

**Comment by msatul1305** [comment]
@rashil2000

**Comment by rashil2000** [comment]
@msatul1305 @meganindya 
Yes you can, to improve the overall look and feel of the website. This would then come under #2
