### ISSUE TITLE
Adding Templates and changing file names

### ISSUE THREAD

**Issue by crusader2000** [rashil2000/d-syfer#7]
It will be easier to add a template so that anyone who wants to contribute by adding an article can easily do so

Adding php for header and footer will be good as it will help cleaning up the code and adding new features/articles

**Comment by crusader2000** [comment]
UPDATE:
To run a php code there are some software installations required . Alternative to this will be to use a javascript file
And that s what I have done

**Comment by rashil2000** [comment]
Cool! If you've written something, make a PR. I'll review it.

**Comment by crusader2000** [comment]
Yeah sending the PR in 10  minutes.

**Comment by rashil2000** [comment]
Also, I'll be closing this issue and merging it with #1 , since this comes under 'Better file management'.

**Comment by crusader2000** [comment]
The PR for this is #8
